apiVersion: apps/v1
kind: Deployment 
metadata:
  name: front-end-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: front
  template:
    metadata:
      labels:
        component: front
    spec:
      containers:
        - name: react-front-end
          image: scott2srikanth/realgrand-frontend:latest
          ports:
            - containerPort: 80

            

kind: Service 
metadata:
  name: front-node-port

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31515
      
  selector:
    component: front
